### ISSUE TITLE
why Fatal Exception  ??

### ISSUE THREAD

**Issue by Ngmong** [HausnerR/ffmpeg-android-example#1]
02-07 23:32:41.138 23967-23967/pl.pachciarek.ffmpeg_android_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: pl.pachciarek.ffmpeg_android_example, PID: 23967
                                                                                      java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/pl.pachciarek.ffmpeg_android_example-1/base.apk"],nativeLibraryDirectories=[/data/app/pl.pachciarek.ffmpeg_android_example-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libffmpeg-test.so"
                                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                                          at pl.pachciarek.ffmpeg_android_example.FFmpegTest.<clinit>(FFmpegTest.java:33)
                                                                                          at pl.pachciarek.ffmpeg_android_example.MainActivity$1.onClick(MainActivity.java:31)
                                                                                          at android.view.View.performClick(View.java:5697)
                                                                                          at android.widget.TextView.performClick(TextView.java:10826)
                                                                                          at android.view.View$PerformClick.run(View.java:22526)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Ngmong** [comment]
I did so in the following order.

1. Make sure paths to SDK and NDK in local.properties are valid,
2. Make sure paths to pre-builded ffmpeg in Android.mk are valid,
3. Push test.mp4 to your phone internal storage root folder,
4. Build and run app.
However, after executing the startrendering, the fatal error happened.
after executing the startrendering, the fatal error happened.
